export type Product = {
  id?: string;
  sku: string;
  brand: string | null;
  category: string | null;
  season: string | null;
  size: string | null;
  color: string | null;
  material: string | null;
  condition: string | null;
  status: string | null;
  purchase_price: number | null;
  sale_price: number | null;
  discount_percent: number | null;
  target_country: string | null;
  sales_channel: string | null;
  designer_level: string | null;
  style_key?: string | null;
  pattern?: string | null;
  occasion?: string | null;
  era?: string | null;
  rarity?: string | null;
  authenticity_status: string | null;
  notes: string | null;
  trend_score?: number | null;
  storage_location?: string | null;
  purchase_source?: string | null;
  sold_at?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type Expense = {
  id?: string;
  expense_date: string;
  category: string | null;
  description: string | null;
  supplier: string | null;
  invoice_number: string | null;
  net_amount: number | null;
  vat_rate: number | null;
  gross_amount: number | null;
  payment_method: string | null;
  receipt_available: boolean | null;
  tax_deductible: string | null;
  recurring: string | null;
  notes: string | null;
  created_at?: string;
  updated_at?: string;
};
